version: "3.9"  # optional since v1.27.0
services:

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    
  web:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DEBUG: 'true'
      PORT: '8010' 
      API_SERVER_ADDR: ":8010"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: warehouse
      DB_PASSWORD: postgres
      DB_USER: admin
      DATABASE_URL: postgresql://admin:postgres@db:5432/warehouse?sslmode=disable
    ports:
      - "8010:8010"
    depends_on:
      - db
    links:
      - db

volumes:
  data:
